#!/usr/bin/env python3
"""Pack several mini-programs into ONE installer you can push in one go.

Why this exists: the phone app uploads exactly one file at a time (its file
input has no `multiple`), so installing five mini-programs means five rounds of
"pick file + type a name + type a title + push". This turns that into one push.

How it works: each app source is embedded verbatim in a triple-quoted string,
and the installer writes them to /apps/<name>/{app.py,meta.json} on the device,
then asks the shell to re-read its app list so the menu updates immediately.

No base64: base64 would cost +33%, and these sources contain no ''' and no
backslash, so they can be embedded as-is. The generator refuses to run if that
ever stops being true, rather than silently producing a broken bundle.

Usage:
    python3 _bundle.py --name "Bundle A" --out bundle_a.py reaction metronome memory
    python3 _bundle.py --list
"""

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

MAX_APP = 32768          # mirrors config.MAX_APP_SIZE on the device

HEAD = '''"""%(title)s - installs %(n)d mini-programs in one push.

Push this single file, run it, and the apps appear in the menu.

Generated by _bundle.py - do not hand-edit; regenerate instead.
ASCII-only and kept under the device's 32 kB per-app limit.
"""

import gc
import os

TITLE = "%(title)s"

BG = 0x0000
BAR = 0x18E3
SEP = 0x39E7
ACC = 0x07FF
GRN = 0x07E0
RED = 0xF800
DIM = 0x8410
WHT = 0xFFFF

APPS = (
'''

ITEM = '    ("%s", "%s",\n%s),\n'

TAIL = ''')


def _put(path, text):
    f = open(path, "w")
    f.write(text)
    f.close()


def setup(ctx):
    l = ctx.lcd
    l.fill(BG)
    l.fill_rect(0, 0, ctx.w, 21, BAR)
    l.text2x("INSTALL", 8, 3, ACC, BAR)
    l.fill_rect(0, 21, ctx.w, 1, SEP)
    l.text_center("packing %d apps" % len(APPS), 34, DIM, BG, 1)

    done = 0
    bad = 0
    firsterr = ""
    total = len(APPS)
    for i in range(total):
        name, title, src = APPS[i]
        l.fill_rect(0, 56, ctx.w, 40, BG)
        l.text_center("%d / %d" % (i + 1, total), 58, WHT, BG, 2)
        l.text_center(name[:20], 84, ACC, BG, 1)
        l.progress(16, 120, 208, 16, i * 100 // total, GRN, BG)
        try:
            d = "/apps/" + name
            try:
                os.mkdir(d)
            except OSError:
                pass
            _put(d + "/app.py", src)
            _put(d + "/meta.json", '{"title": "%s"}' % title)
            done += 1
        except Exception as e:
            bad += 1
            if not firsterr:
                firsterr = "%s: %s" % (name, type(e).__name__)
        gc.collect()

    l.progress(16, 120, 208, 16, 100, GRN if not bad else RED, BG)
    l.fill_rect(0, 168, ctx.w, 90, BG)
    l.text_center("%d installed" % done, 172, GRN, BG, 2)
    if bad:
        l.text_center("%d FAILED" % bad, 200, RED, BG, 1)
        l.text_center(firsterr[:28], 216, WHT, BG, 1)
    l.text_center("leave this app to see", 232, DIM, BG, 1)
    l.text_center("them in the menu", 246, DIM, BG, 1)

    # make the launcher re-read /apps right away, no reboot needed
    try:
        ctx.shell.refresh_apps()
    except Exception:
        pass


def loop(ctx):
    pass


def on_key(ctx, key):
    if key == "ok":
        ctx.exit()


def teardown(ctx):
    pass
'''


def load_app(name):
    path = os.path.join(HERE, name + ".py")
    if not os.path.exists(path):
        sys.exit("找不到 %s" % path)
    src = open(path, encoding="utf-8").read()
    if "'''" in src:
        sys.exit("%s 里出现了 '''，无法安全嵌入三引号字符串" % name)
    if "\\" in src:
        sys.exit("%s 里有反斜杠，嵌入后转义会失真" % name)
    if src.rstrip().endswith("'''"):
        sys.exit("%s 结尾是三引号" % name)
    return src


def title_of(name, src):
    for line in src.splitlines():
        if line.startswith("TITLE ="):
            return line.split("=", 1)[1].strip().strip('"').strip("'")
    return name.capitalize()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("apps", nargs="*")
    ap.add_argument("--name", default="Bundle")
    ap.add_argument("--out", default=None)
    ap.add_argument("--list", action="store_true", help="列出可用的小程序")
    args = ap.parse_args()

    if args.list:
        avail = sorted(f[:-3] for f in os.listdir(HERE)
                       if f.endswith(".py") and not f.startswith("_"))
        print("可用: %s" % " ".join(avail))
        return 0

    if not args.apps:
        ap.error("至少要给一个小程序名，或用 --list 看看有哪些")

    body = ""
    names = []
    for a in args.apps:
        src = load_app(a)
        t = title_of(a, src)
        # a trailing newline inside the literal keeps the written file tidy
        body += ITEM % (a, t, "'''" + src + "'''")
        names.append((a, len(src.encode())))

    out = args.out or ("bundle_" + args.name.lower().replace(" ", "_") + ".py")
    text = HEAD % {"title": args.name, "n": len(names)} + body + TAIL
    data = text.encode()
    if len(data) > MAX_APP:
        sys.exit("打包后 %d 字节，超过设备上限 %d。减少几个小程序，或拆成多个包。"
                 % (len(data), MAX_APP))
    with open(os.path.join(HERE, out), "w", encoding="utf-8") as f:
        f.write(text)

    print("已生成 %s" % out)
    print("  包含 %d 个: %s" % (len(names), ", ".join(n for n, _ in names)))
    print("  源码合计 %d 字节 -> 打包后 %d 字节 (%d 分片 @160B)"
          % (sum(s for _, s in names), len(data), (len(data) + 159) // 160))
    print("  设备上限 %d，占用 %.0f%%" % (MAX_APP, len(data) * 100.0 / MAX_APP))
    return 0


if __name__ == "__main__":
    sys.exit(main())
